/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RotatingPanelRouteImport } from './routes/rotatingPanel'
import { Route as OverlayIdRouteImport } from './routes/overlay/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatingPanelRoute = RotatingPanelRouteImport.update({
  id: '/rotatingPanel',
  path: '/rotatingPanel',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayIdRoute = OverlayIdRouteImport.update({
  id: '/overlay/$id',
  path: '/overlay/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/overlay/$id': typeof OverlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/overlay/$id': typeof OverlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/overlay/$id': typeof OverlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rotatingPanel' | '/overlay/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rotatingPanel' | '/overlay/$id'
  id: '__root__' | '/' | '/rotatingPanel' | '/overlay/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RotatingPanelRoute: typeof RotatingPanelRoute
  OverlayIdRoute: typeof OverlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotatingPanel': {
      id: '/rotatingPanel'
      path: '/rotatingPanel'
      fullPath: '/rotatingPanel'
      preLoaderRoute: typeof RotatingPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$id': {
      id: '/overlay/$id'
      path: '/overlay/$id'
      fullPath: '/overlay/$id'
      preLoaderRoute: typeof OverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RotatingPanelRoute: RotatingPanelRoute,
  OverlayIdRoute: OverlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
