/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RotatingPanelRouteImport } from './routes/rotatingPanel'
import { Route as DebugAudioRouteImport } from './routes/debug/audio'
import { Route as OverlaysIdRouteImport } from './routes/overlays/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatingPanelRoute = RotatingPanelRouteImport.update({
  id: '/rotatingPanel',
  path: '/rotatingPanel',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAudioRoute = DebugAudioRouteImport.update({
  id: '/debug/audio',
  path: '/debug/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysIdRoute = OverlaysIdRouteImport.update({
  id: '/overlays/$id',
  path: '/overlays/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/debug/audio': typeof DebugAudioRoute
  '/overlays/$id': typeof OverlaysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/debug/audio': typeof DebugAudioRoute
  '/overlays/$id': typeof OverlaysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/debug/audio': typeof DebugAudioRoute
  '/overlays/$id': typeof OverlaysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rotatingPanel' | '/debug/audio' | '/overlays/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rotatingPanel' | '/debug/audio' | '/overlays/$id'
  id: '__root__' | '/' | '/rotatingPanel' | '/debug/audio' | '/overlays/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RotatingPanelRoute: typeof RotatingPanelRoute
  DebugAudioRoute: typeof DebugAudioRoute
  OverlaysIdRoute: typeof OverlaysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotatingPanel': {
      id: '/rotatingPanel'
      path: '/rotatingPanel'
      fullPath: '/rotatingPanel'
      preLoaderRoute: typeof RotatingPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/audio': {
      id: '/debug/audio'
      path: '/debug/audio'
      fullPath: '/debug/audio'
      preLoaderRoute: typeof DebugAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/$id': {
      id: '/overlays/$id'
      path: '/overlays/$id'
      fullPath: '/overlays/$id'
      preLoaderRoute: typeof OverlaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RotatingPanelRoute: RotatingPanelRoute,
  DebugAudioRoute: DebugAudioRoute,
  OverlaysIdRoute: OverlaysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
