/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RotatingPanelRouteImport } from './routes/rotatingPanel'
import { Route as TestRendererRouteImport } from './routes/test-renderer'
import { Route as OverlayIdRouteImport } from './routes/overlay/$id'
import { Route as OverlaysIdRouteImport } from './routes/overlays/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatingPanelRoute = RotatingPanelRouteImport.update({
  id: '/rotatingPanel',
  path: '/rotatingPanel',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRendererRoute = TestRendererRouteImport.update({
  id: '/test-renderer',
  path: '/test-renderer',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayIdRoute = OverlayIdRouteImport.update({
  id: '/overlay/$id',
  path: '/overlay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysIdRoute = OverlaysIdRouteImport.update({
  id: '/overlays/$id',
  path: '/overlays/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/test-renderer': typeof TestRendererRoute
  '/overlay/$id': typeof OverlayIdRoute
  '/overlays/$id': typeof OverlaysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/test-renderer': typeof TestRendererRoute
  '/overlay/$id': typeof OverlayIdRoute
  '/overlays/$id': typeof OverlaysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rotatingPanel': typeof RotatingPanelRoute
  '/test-renderer': typeof TestRendererRoute
  '/overlay/$id': typeof OverlayIdRoute
  '/overlays/$id': typeof OverlaysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/rotatingPanel' | '/test-renderer' | '/overlay/$id' | '/overlays/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/rotatingPanel' | '/test-renderer' | '/overlay/$id' | '/overlays/$id'
  id:
    | '__root__'
    | '/'
    | '/rotatingPanel'
    | '/test-renderer'
    | '/overlay/$id'
    | '/overlays/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RotatingPanelRoute: typeof RotatingPanelRoute
  TestRendererRoute: typeof TestRendererRoute
  OverlayIdRoute: typeof OverlayIdRoute
  OverlaysIdRoute: typeof OverlaysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotatingPanel': {
      id: '/rotatingPanel'
      path: '/rotatingPanel'
      fullPath: '/rotatingPanel'
      preLoaderRoute: typeof RotatingPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-renderer': {
      id: '/test-renderer'
      path: '/test-renderer'
      fullPath: '/test-renderer'
      preLoaderRoute: typeof TestRendererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$id': {
      id: '/overlay/$id'
      path: '/overlay/$id'
      fullPath: '/overlay/$id'
      preLoaderRoute: typeof OverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/$id': {
      id: '/overlays/$id'
      path: '/overlays/$id'
      fullPath: '/overlays/$id'
      preLoaderRoute: typeof OverlaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RotatingPanelRoute: RotatingPanelRoute,
  TestRendererRoute: TestRendererRoute,
  OverlayIdRoute: OverlayIdRoute,
  OverlaysIdRoute: OverlaysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
