/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as ObsRouteImport } from './routes/obs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AlertsIdRouteImport } from './routes/alerts/$id'
import { Route as AlertsPresetsRouteImport } from './routes/alerts/presets'
import { Route as OverlaysIndexRouteImport } from './routes/overlays/index'
import { Route as OverlaysIdRouteImport } from './routes/overlays/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsRoute = ObsRouteImport.update({
  id: '/obs',
  path: '/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsPresetsRoute = AlertsPresetsRouteImport.update({
  id: '/alerts/presets',
  path: '/alerts/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysIndexRoute = OverlaysIndexRouteImport.update({
  id: '/overlays/',
  path: '/overlays/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysIdRoute = OverlaysIdRouteImport.update({
  id: '/overlays/$id',
  path: '/overlays/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audio': typeof AudioRoute
  '/obs': typeof ObsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/presets': typeof AlertsPresetsRoute
  '/overlays/$id': typeof OverlaysIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/overlays/': typeof OverlaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audio': typeof AudioRoute
  '/obs': typeof ObsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/presets': typeof AlertsPresetsRoute
  '/overlays/$id': typeof OverlaysIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/overlays': typeof OverlaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audio': typeof AudioRoute
  '/obs': typeof ObsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/presets': typeof AlertsPresetsRoute
  '/overlays/$id': typeof OverlaysIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/overlays/': typeof OverlaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/audio'
    | '/obs'
    | '/settings'
    | '/alerts/$id'
    | '/alerts/presets'
    | '/overlays/$id'
    | '/alerts/'
    | '/overlays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/audio'
    | '/obs'
    | '/settings'
    | '/alerts/$id'
    | '/alerts/presets'
    | '/overlays/$id'
    | '/alerts'
    | '/overlays'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/audio'
    | '/obs'
    | '/settings'
    | '/alerts/$id'
    | '/alerts/presets'
    | '/overlays/$id'
    | '/alerts/'
    | '/overlays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AudioRoute: typeof AudioRoute
  ObsRoute: typeof ObsRoute
  SettingsRoute: typeof SettingsRoute
  AlertsIdRoute: typeof AlertsIdRoute
  AlertsPresetsRoute: typeof AlertsPresetsRoute
  OverlaysIdRoute: typeof OverlaysIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  OverlaysIndexRoute: typeof OverlaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs': {
      id: '/obs'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof ObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/presets': {
      id: '/alerts/presets'
      path: '/alerts/presets'
      fullPath: '/alerts/presets'
      preLoaderRoute: typeof AlertsPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/': {
      id: '/overlays/'
      path: '/overlays'
      fullPath: '/overlays/'
      preLoaderRoute: typeof OverlaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/$id': {
      id: '/overlays/$id'
      path: '/overlays/$id'
      fullPath: '/overlays/$id'
      preLoaderRoute: typeof OverlaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AudioRoute: AudioRoute,
  ObsRoute: ObsRoute,
  SettingsRoute: SettingsRoute,
  AlertsIdRoute: AlertsIdRoute,
  AlertsPresetsRoute: AlertsPresetsRoute,
  OverlaysIdRoute: OverlaysIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  OverlaysIndexRoute: OverlaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
