/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObsRouteImport } from './routes/obs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AlertsIdRouteImport } from './routes/alerts/$id'
import { Route as AlertsPresetsRouteImport } from './routes/alerts/presets'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as AudioIndexRouteImport } from './routes/audio/index'
import { Route as DonationsIndexRouteImport } from './routes/donations/index'
import { Route as DonationsHistoryRouteImport } from './routes/donations/history'
import { Route as DonationsSettingsRouteImport } from './routes/donations/settings'
import { Route as OverlaysIndexRouteImport } from './routes/overlays/index'
import { Route as OverlaysIdRouteImport } from './routes/overlays/$id'
import { Route as DonateCreatorIdIndexRouteImport } from './routes/donate/$creatorId/index'
import { Route as DonateCreatorIdPaymentDonationIdRouteImport } from './routes/donate/$creatorId/payment/$donationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsRoute = ObsRouteImport.update({
  id: '/obs',
  path: '/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsPresetsRoute = AlertsPresetsRouteImport.update({
  id: '/alerts/presets',
  path: '/alerts/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIndexRoute = AudioIndexRouteImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsIndexRoute = DonationsIndexRouteImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsHistoryRoute = DonationsHistoryRouteImport.update({
  id: '/donations/history',
  path: '/donations/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsSettingsRoute = DonationsSettingsRouteImport.update({
  id: '/donations/settings',
  path: '/donations/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysIndexRoute = OverlaysIndexRouteImport.update({
  id: '/overlays/',
  path: '/overlays/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysIdRoute = OverlaysIdRouteImport.update({
  id: '/overlays/$id',
  path: '/overlays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCreatorIdIndexRoute = DonateCreatorIdIndexRouteImport.update({
  id: '/donate/$creatorId/',
  path: '/donate/$creatorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCreatorIdPaymentDonationIdRoute =
  DonateCreatorIdPaymentDonationIdRouteImport.update({
    id: '/donate/$creatorId/payment/$donationId',
    path: '/donate/$creatorId/payment/$donationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obs': typeof ObsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/presets': typeof AlertsPresetsRoute
  '/donations/history': typeof DonationsHistoryRoute
  '/donations/settings': typeof DonationsSettingsRoute
  '/overlays/$id': typeof OverlaysIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/audio/': typeof AudioIndexRoute
  '/donations/': typeof DonationsIndexRoute
  '/overlays/': typeof OverlaysIndexRoute
  '/donate/$creatorId/': typeof DonateCreatorIdIndexRoute
  '/donate/$creatorId/payment/$donationId': typeof DonateCreatorIdPaymentDonationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obs': typeof ObsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/presets': typeof AlertsPresetsRoute
  '/donations/history': typeof DonationsHistoryRoute
  '/donations/settings': typeof DonationsSettingsRoute
  '/overlays/$id': typeof OverlaysIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/audio': typeof AudioIndexRoute
  '/donations': typeof DonationsIndexRoute
  '/overlays': typeof OverlaysIndexRoute
  '/donate/$creatorId': typeof DonateCreatorIdIndexRoute
  '/donate/$creatorId/payment/$donationId': typeof DonateCreatorIdPaymentDonationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obs': typeof ObsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/presets': typeof AlertsPresetsRoute
  '/donations/history': typeof DonationsHistoryRoute
  '/donations/settings': typeof DonationsSettingsRoute
  '/overlays/$id': typeof OverlaysIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/audio/': typeof AudioIndexRoute
  '/donations/': typeof DonationsIndexRoute
  '/overlays/': typeof OverlaysIndexRoute
  '/donate/$creatorId/': typeof DonateCreatorIdIndexRoute
  '/donate/$creatorId/payment/$donationId': typeof DonateCreatorIdPaymentDonationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obs'
    | '/settings'
    | '/alerts/$id'
    | '/alerts/presets'
    | '/donations/history'
    | '/donations/settings'
    | '/overlays/$id'
    | '/alerts/'
    | '/assets/'
    | '/audio/'
    | '/donations/'
    | '/overlays/'
    | '/donate/$creatorId/'
    | '/donate/$creatorId/payment/$donationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obs'
    | '/settings'
    | '/alerts/$id'
    | '/alerts/presets'
    | '/donations/history'
    | '/donations/settings'
    | '/overlays/$id'
    | '/alerts'
    | '/assets'
    | '/audio'
    | '/donations'
    | '/overlays'
    | '/donate/$creatorId'
    | '/donate/$creatorId/payment/$donationId'
  id:
    | '__root__'
    | '/'
    | '/obs'
    | '/settings'
    | '/alerts/$id'
    | '/alerts/presets'
    | '/donations/history'
    | '/donations/settings'
    | '/overlays/$id'
    | '/alerts/'
    | '/assets/'
    | '/audio/'
    | '/donations/'
    | '/overlays/'
    | '/donate/$creatorId/'
    | '/donate/$creatorId/payment/$donationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObsRoute: typeof ObsRoute
  SettingsRoute: typeof SettingsRoute
  AlertsIdRoute: typeof AlertsIdRoute
  AlertsPresetsRoute: typeof AlertsPresetsRoute
  DonationsHistoryRoute: typeof DonationsHistoryRoute
  DonationsSettingsRoute: typeof DonationsSettingsRoute
  OverlaysIdRoute: typeof OverlaysIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  AudioIndexRoute: typeof AudioIndexRoute
  DonationsIndexRoute: typeof DonationsIndexRoute
  OverlaysIndexRoute: typeof OverlaysIndexRoute
  DonateCreatorIdIndexRoute: typeof DonateCreatorIdIndexRoute
  DonateCreatorIdPaymentDonationIdRoute: typeof DonateCreatorIdPaymentDonationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs': {
      id: '/obs'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof ObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/presets': {
      id: '/alerts/presets'
      path: '/alerts/presets'
      fullPath: '/alerts/presets'
      preLoaderRoute: typeof AlertsPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/': {
      id: '/audio/'
      path: '/audio'
      fullPath: '/audio/'
      preLoaderRoute: typeof AudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/': {
      id: '/donations/'
      path: '/donations'
      fullPath: '/donations/'
      preLoaderRoute: typeof DonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/history': {
      id: '/donations/history'
      path: '/donations/history'
      fullPath: '/donations/history'
      preLoaderRoute: typeof DonationsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/settings': {
      id: '/donations/settings'
      path: '/donations/settings'
      fullPath: '/donations/settings'
      preLoaderRoute: typeof DonationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/': {
      id: '/overlays/'
      path: '/overlays'
      fullPath: '/overlays/'
      preLoaderRoute: typeof OverlaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/$id': {
      id: '/overlays/$id'
      path: '/overlays/$id'
      fullPath: '/overlays/$id'
      preLoaderRoute: typeof OverlaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$creatorId/': {
      id: '/donate/$creatorId/'
      path: '/donate/$creatorId'
      fullPath: '/donate/$creatorId/'
      preLoaderRoute: typeof DonateCreatorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$creatorId/payment/$donationId': {
      id: '/donate/$creatorId/payment/$donationId'
      path: '/donate/$creatorId/payment/$donationId'
      fullPath: '/donate/$creatorId/payment/$donationId'
      preLoaderRoute: typeof DonateCreatorIdPaymentDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObsRoute: ObsRoute,
  SettingsRoute: SettingsRoute,
  AlertsIdRoute: AlertsIdRoute,
  AlertsPresetsRoute: AlertsPresetsRoute,
  DonationsHistoryRoute: DonationsHistoryRoute,
  DonationsSettingsRoute: DonationsSettingsRoute,
  OverlaysIdRoute: OverlaysIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  AudioIndexRoute: AudioIndexRoute,
  DonationsIndexRoute: DonationsIndexRoute,
  OverlaysIndexRoute: OverlaysIndexRoute,
  DonateCreatorIdIndexRoute: DonateCreatorIdIndexRoute,
  DonateCreatorIdPaymentDonationIdRoute: DonateCreatorIdPaymentDonationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
