/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamOverlay3DRouteImport } from './routes/StreamOverlay3D'
import { Route as DonationAlertRouteImport } from './routes/donationAlert'
import { Route as RotatingPanelRouteImport } from './routes/rotatingPanel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamOverlay3DRoute = StreamOverlay3DRouteImport.update({
  id: '/StreamOverlay3D',
  path: '/StreamOverlay3D',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationAlertRoute = DonationAlertRouteImport.update({
  id: '/donationAlert',
  path: '/donationAlert',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatingPanelRoute = RotatingPanelRouteImport.update({
  id: '/rotatingPanel',
  path: '/rotatingPanel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/StreamOverlay3D': typeof StreamOverlay3DRoute
  '/donationAlert': typeof DonationAlertRoute
  '/rotatingPanel': typeof RotatingPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/StreamOverlay3D': typeof StreamOverlay3DRoute
  '/donationAlert': typeof DonationAlertRoute
  '/rotatingPanel': typeof RotatingPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/StreamOverlay3D': typeof StreamOverlay3DRoute
  '/donationAlert': typeof DonationAlertRoute
  '/rotatingPanel': typeof RotatingPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/StreamOverlay3D' | '/donationAlert' | '/rotatingPanel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/StreamOverlay3D' | '/donationAlert' | '/rotatingPanel'
  id:
    '__root__' | '/' | '/StreamOverlay3D' | '/donationAlert' | '/rotatingPanel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StreamOverlay3DRoute: typeof StreamOverlay3DRoute
  DonationAlertRoute: typeof DonationAlertRoute
  RotatingPanelRoute: typeof RotatingPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/StreamOverlay3D': {
      id: '/StreamOverlay3D'
      path: '/StreamOverlay3D'
      fullPath: '/StreamOverlay3D'
      preLoaderRoute: typeof StreamOverlay3DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donationAlert': {
      id: '/donationAlert'
      path: '/donationAlert'
      fullPath: '/donationAlert'
      preLoaderRoute: typeof DonationAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotatingPanel': {
      id: '/rotatingPanel'
      path: '/rotatingPanel'
      fullPath: '/rotatingPanel'
      preLoaderRoute: typeof RotatingPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StreamOverlay3DRoute: StreamOverlay3DRoute,
  DonationAlertRoute: DonationAlertRoute,
  RotatingPanelRoute: RotatingPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
